export const CAMERA_CONSTANTS = {
  FOV: 75,
  ASPECT_RATIO: 1,
  NEAR_PLANE: 0.1,
  FAR_PLANE: 1000,
  
  DISTANCE_MULTIPLIER: 1.5,
  POSITION_OFFSET: {
    X_FACTOR: 0.7,
    Y_FACTOR: 0.5,
    Z_FACTOR: 0.7
  },
  
  MIN_DISTANCE: 2,
  MAX_DISTANCE: 20,
  
  MIN_POLAR_ANGLE: 0.1,
  MAX_POLAR_ANGLE: Math.PI - 0.1,
  
  ORBIT_CONTROLS: {
    DAMPING_FACTOR: 0.05,
    MOBILE_DAMPING_FACTOR: 0.1,
    ROTATE_SPEED: 1.0,
    ZOOM_SPEED: 1.2,
    PAN_SPEED: 0.8,
    MAX_POLAR_ANGLE_FACTOR: 0.9,
    MIN_POLAR_ANGLE_FACTOR: 0.1
  }
} as const;
