export const TOUCH_CONSTANTS = {
  ROTATION_SPEED: 0.005,
  ZOOM_SPEED: 0.01,
  ZOOM_SENSITIVITY_MULTIPLIER: 5,
  TWO_FINGER_ROTATION_MULTIPLIER: 0.5,
  
  MOBILE_BREAKPOINT: 768,
  
  PINCH_ZOOM_SCALE: 0.01,
  
  INITIAL_DISTANCE: 0 as number,
  INITIAL_ANGLE: 0 as number,
  
  MAX_TOUCH_POINTS_THRESHOLD: 0
} as const;
